mpd: 3.2ify the rc.d entry.

diff --git a/mpd/mpd b/mpd/mpd
--- a/mpd/mpd
+++ b/mpd/mpd
@@ -1,9 +1,37 @@
 #!/bin/sh
-# /etc/rc.d/mpd: start/stop mpd
+#
+# /etc/rc.d/mpd: start/stop mpd daemon
+#
+
+SSD=/sbin/start-stop-daemon
+PROG=/usr/bin/mpd
+PID=/var/run/mpd.pid
+OPTS=""
 
 case $1 in
-	start) /usr/bin/mpd ;;
-	stop) kill -9 $(pidof /usr/bin/mpd) ;;
-	restart) $0 stop; sleep 2; $0 start ;;
-	*) echo "Usage: $0 [start|stop|restart]" ;;
+start)
+	$SSD --start --pidfile $PID --exec $PROG -- $OPTS
+	;;
+stop)
+	$SSD --stop --retry 10 --pidfile $PID
+	;;
+restart)
+	$0 stop
+	$0 start
+	;;
+status)
+	$SSD --status --pidfile $PID
+	case $? in
+	0) echo "$PROG is running with pid $(cat $PID)" ;;
+	1) echo "$PROG is not running but the pid file $PID exists" ;;
+	3) echo "$PROG is not running" ;;
+	4) echo "Unable to determine the program status" ;;
+	esac
+	;;
+*)
+	echo "usage: $0 [start|stop|restart|status]"
+	;;
 esac
+
+# End of file
+
